name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: prettier
      run: npm run prettier
    - name: npm test
      run: npm run test
